"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination } from "swiper/modules";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

export type Page = "home" | "products" | "detail" | "accessories" | "technology" | "story" | "journal" | "support" | "shipping" | "warranty" | "register" | "cart";
type Product = { id:string; name:string; color:string; colorKo:string; note:string; price:number; image:string; hex:string };
type CartItem = Product & { qty:number };

const products:Product[] = [
  {id:"halo-black",name:"HALO X1",color:"BLACK",colorKo:"새틴 블랙",note:"Spatial ANC · 60H",price:389000,image:"/products/halo-x1-black.png",hex:"#171719"},
  {id:"halo-white",name:"HALO X1",color:"WHITE",colorKo:"펄 화이트",note:"Spatial ANC · 60H",price:389000,image:"/products/halo-x1-white.png",hex:"#eeeae1"},
  {id:"halo-blue",name:"HALO X1",color:"LIGHT BLUE",colorKo:"아이스 블루",note:"Spatial ANC · 60H",price:389000,image:"/products/halo-x1-lightblue.png",hex:"#a9d4ed"},
  {id:"halo-violet",name:"HALO X1",color:"VIOLET",colorKo:"뮤트 바이올렛",note:"Spatial ANC · 60H",price:389000,image:"/products/halo-x1-violet.png",hex:"#8d68aa"},
];
const won = (value:number) => `₩${value.toLocaleString("ko-KR")}`;

function ProductImage({src,className="",alt="AURALAB HALO X1 헤드셋"}:{src:string;className?:string;alt?:string}){
  return <img className={`product-shot ${className}`} src={src} alt={alt} loading={className.includes("hero")?"eager":"lazy"}/>;
}

function Header({count}:{count:number}){
  const [open,setOpen]=useState(false);
  return <>
    <header className="site-header"><div className="max nav-wrap">
      <a className="logo" href="/">AURA<span className="logo-dot">LAB</span></a>
      <nav className="gnb" aria-label="주요 메뉴">
        <div className="gnb-group"><a href="/products">PRODUCTS</a><div className="mega"><a href="/products"><b>ALL PRODUCTS</b><span>모든 컬러 보기</span></a><a href="/product/halo-x1"><b>HALO X1</b><span>플래그십 헤드셋</span></a><a href="/accessories"><b>ACCESSORIES</b><span>케이스 & 케이블</span></a></div></div>
        <div className="gnb-group"><a href="/story">DISCOVER</a><div className="mega"><a href="/story"><b>OUR STORY</b><span>우리가 만드는 고요</span></a><a href="/technology"><b>TECHNOLOGY</b><span>몰입을 만드는 기술</span></a><a href="/journal"><b>JOURNAL</b><span>사운드와 일상</span></a></div></div>
        <a href="/support">SUPPORT</a>
      </nav>
      <div className="nav-actions"><a className="bag-link" href="/cart" aria-label={`장바구니 ${count}개`}>BAG <span>{count}</span></a><button className="menu-btn" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="메뉴 열기"><i/><i/></button></div>
    </div></header>
    <div className={`mobile-menu ${open?"open":""}`}><div className="mobile-menu-inner"><a href="/products">Products <small>01</small></a><a href="/story">Our Story <small>02</small></a><a href="/technology">Technology <small>03</small></a><a href="/journal">Journal <small>04</small></a><a href="/support">Support <small>05</small></a></div></div>
  </>;
}

function Footer(){return <footer className="footer"><div className="max"><div className="footer-top"><div className="footer-brand"><h3>AURA<span className="lime">LAB</span></h3><span>공간을 넘어, 감각에 닿는 사운드.</span></div><div><h4>SHOP</h4><a href="/products">전체 제품</a><a href="/product/halo-x1">HALO X1</a><a href="/accessories">액세서리</a></div><div><h4>DISCOVER</h4><a href="/story">Our Story</a><a href="/technology">Technology</a><a href="/journal">Journal</a></div><div><h4>HELP</h4><a href="/support">고객지원</a><a href="/shipping">배송 & 반품</a><a href="/register">제품 등록</a></div></div><div className="footer-bottom"><span>© 2026 AURALAB AUDIO. ALL RIGHTS RESERVED.</span><span>SEOUL — KOREA</span></div></div></footer>}

function ProductCard({p,i}:{p:Product;i:number}){return <a className="product-card" href={`/product/halo-x1?color=${p.color.toLowerCase().replace(" ","-")}`}><div className="product-art" data-num={`0${i+1}`}><ProductImage src={p.image} alt={`${p.name} ${p.colorKo}`}/><span className="color-dot" style={{background:p.hex}}/></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.color} · {p.note}</p></div><b>{won(p.price)}</b></div></a>}

function Home(){return <main>
  <section className="hero"><div className="max"><div className="hero-copy"><div className="eyebrow lime">NEW / HALO X1</div><h1>HEAR<span>BEYOND.</span></h1><div className="hero-sub"><p>침묵은 더 깊게, 디테일은 더 선명하게.<br/>당신만의 사운드 공간을 완성하세요.</p><a className="cta" href="/product/halo-x1?color=white">DISCOVER <b>↗</b></a></div></div></div><ProductImage src="/products/halo-x1-white.png" className="hero-product"/><div className="hero-model">IMMERSIVE HEADSET<strong>HALO X1</strong></div><div className="scroll-mark">SCROLL TO EXPLORE ↓</div></section>
  <section className="sound-lab"><div className="sound-pin"><div className="max sound-grid"><div className="sound-copy"><div className="eyebrow">01 / DESIGNED FOR SILENCE</div><h2>NOTHING<br/>BUT <span className="lime">SOUND.</span></h2><p>12개의 정밀 마이크가 외부 소음을 초당 48,000번 분석합니다. Adaptive Silence™가 환경에 맞춰 실시간으로 반응해 음악만 남깁니다.</p><div className="stat-row"><div className="stat"><b>−42 dB</b><small>NOISE REDUCTION</small></div><div className="stat"><b>60 H</b><small>BATTERY LIFE</small></div><div className="stat"><b>218 g</b><small>ULTRA LIGHT</small></div></div></div><div className="sound-visual"><div className="rings"/><div className="sound-product-frame"><ProductImage src="/products/halo-x1-black.png"/></div></div></div></div></section>
  <section className="products"><div className="max"><div className="section-head"><div><div className="eyebrow lime">02 / FIND YOUR COLOR</div><h2>THE LINEUP.</h2></div><p>하나의 정교한 사운드, 네 가지 개성. 당신의 리듬과 가장 닮은 컬러를 선택하세요.</p></div><Swiper className="product-swiper" modules={[Pagination,Autoplay]} spaceBetween={18} slidesPerView={1.12} breakpoints={{650:{slidesPerView:2.1},1050:{slidesPerView:3.05}}} pagination={{type:"progressbar"}} autoplay={{delay:3200,disableOnInteraction:false}}>{products.map((p,i)=><SwiperSlide key={p.id}><ProductCard p={p} i={i}/></SwiperSlide>)}</Swiper></div></section>
  <section className="immersive"><div className="noise-line"/><div className="max"><div className="eyebrow">03 / MADE TO DISAPPEAR</div><h2>FEEL<span>EVERYTHING.</span></h2><div className="quote"><p>“헤드셋을 쓰고 있다는 사실조차 잊는 순간, 진짜 몰입이 시작됩니다.”</p><div><a className="cta dark" href="/story">OUR SOUND STORY <b>↗</b></a></div></div></div></section>
</main>}

function SubHero({index,title,copy}:{index:string;title:string;copy:string}){return <section className="sub-hero"><div className="max"><div className="eyebrow lime">{index}</div><h1>{title}</h1><p>{copy}</p></div></section>}
function Products(){return <main><SubHero index="CATALOG / 2026" title="ONE FORM. FOUR MOODS." copy="완성도 높은 하나의 헤드셋을 네 가지 컬러로 만나보세요. 사운드는 같고, 분위기는 완전히 다릅니다."/><section className="catalog"><div className="max"><div className="filter"><button className="chip active">HALO X1</button><a className="chip" href="/accessories">ACCESSORIES</a></div><div className="product-grid">{products.map((p,i)=><ProductCard key={p.id} p={p} i={i}/>)}</div></div></section></main>}

function Detail({add}:{add:(p:Product)=>void}){
  const [selected,setSelected]=useState(1); const [added,setAdded]=useState(false); const p=products[selected];
  useEffect(()=>{const q=new URLSearchParams(window.location.search).get("color");const idx=products.findIndex(x=>x.color.toLowerCase().replace(" ","-")===q);if(idx>=0)setSelected(idx)},[]);
  const addNow=()=>{add(p);setAdded(true);window.setTimeout(()=>setAdded(false),1600)};
  return <main className="detail"><div className="max detail-grid"><div className="detail-visual"><ProductImage src={p.image} className="detail-product" alt={`HALO X1 ${p.colorKo}`}/><div className="detail-counter">0{selected+1} / 04</div></div><div className="detail-copy"><div className="eyebrow lime">FLAGSHIP / 2026</div><h1>HALO<br/>X1.</h1><p>플래그십 사운드와 완벽한 고요함. 정밀 가공 알루미늄과 메모리폼이 하루 종일 이어지는 편안함을 만듭니다.</p><div className="price">{won(p.price)}</div><div className="color-picker"><span>COLOR — <b>{p.colorKo}</b></span><div>{products.map((item,i)=><button key={item.id} className={selected===i?"active":""} style={{"--swatch":item.hex} as React.CSSProperties} onClick={()=>setSelected(i)} aria-label={item.colorKo}/>)}</div></div><div className="options"><div className="option"><span>DELIVERY</span><b>무료 / 1–2일</b></div><div className="option"><span>WARRANTY</span><b>2년</b></div><div className="option"><span>RETURNS</span><b>30일 무료</b></div></div><div className="buybar"><button className="cta" onClick={addNow}>{added?"ADDED TO BAG ✓":"ADD TO BAG"}</button><a className="round" href="/cart" aria-label="장바구니 보기">↗</a></div></div></div></main>}

function Story(){return <main><SubHero index="ABOUT / AURALAB" title="WE DESIGN SILENCE." copy="더 많은 소리가 아니라, 더 중요한 소리를 듣게 하는 것. 그것이 AURALAB이 시작된 이유입니다."/><section className="story-body"><div className="max"><p className="story-lead">서울의 작은 사운드 랩에서 시작해, 우리는 음향 엔지니어링과 산업 디자인의 경계를 지워왔습니다. 기술은 보이지 않아야 하고, 감각만 남아야 한다고 믿습니다.</p><div className="values"><div className="value"><b>01</b><h3>Precision</h3><p>수천 번의 청음과 측정으로 불필요한 왜곡을 제거합니다.</p></div><div className="value"><b>02</b><h3>Quiet Design</h3><p>눈에 띄기보다 사용자의 일상에 자연스럽게 스며듭니다.</p></div><div className="value"><b>03</b><h3>Built to Last</h3><p>교체 가능한 부품과 견고한 소재로 오래 쓰는 제품을 만듭니다.</p></div></div></div></section></main>}
function Technology(){return <main><SubHero index="TECH / ADAPTIVE SILENCE™" title="ENGINEERED FOR IMMERSION." copy="듣고 싶은 소리는 더 가깝게, 원하지 않는 소리는 더 멀리. 12개의 마이크와 독자적인 공간 음향 엔진이 실시간으로 작동합니다."/><section className="tech-body"><div className="max tech-stack"><article><span>01</span><h2>48,000</h2><p>초당 소음 분석 횟수. 주변 환경이 바뀌는 순간에도 자연스럽게 고요함을 유지합니다.</p></article><article><span>02</span><h2>40 mm</h2><p>맞춤 설계된 바이오셀룰로오스 드라이버가 낮은 왜곡과 빠른 반응을 제공합니다.</p></article><article><span>03</span><h2>Spatial</h2><p>머리의 움직임을 추적하는 공간 음향으로 무대 한가운데 있는 듯한 깊이를 만듭니다.</p></article></div></section></main>}
function Journal(){return <main><SubHero index="EDITORIAL / JOURNAL" title="LISTEN CLOSER." copy="사운드와 집중, 그리고 더 나은 일상을 탐구하는 AURALAB의 기록입니다."/><section className="journal-body"><div className="max journal-grid"><article><div className="journal-no">01</div><small>PEOPLE · 8 MIN</small><h2>음악을 설계하는 사람들의 작업실</h2><p>세 명의 프로듀서에게 몰입을 만드는 환경에 관해 물었습니다.</p></article><article><div className="journal-no">02</div><small>GUIDE · 5 MIN</small><h2>노이즈 캔슬링을 더 잘 사용하는 법</h2><p>출퇴근, 작업, 휴식에 맞는 세 가지 리스닝 모드.</p></article><article><div className="journal-no">03</div><small>DESIGN · 6 MIN</small><h2>218g 안에 담긴 편안함</h2><p>HALO X1의 소재와 균형을 결정한 디자인 과정.</p></article></div></section></main>}
function Accessories(){return <main><SubHero index="SHOP / ACCESSORIES" title="COMPLETE THE SET." copy="HALO X1을 더 오래, 더 편리하게 사용할 수 있도록 설계된 액세서리입니다."/><section className="catalog"><div className="max accessory-grid"><article><div className="accessory-art">CASE</div><h2>HALO TRAVEL CASE</h2><p>충격 흡수 하드쉘 · ₩59,000</p></article><article><div className="accessory-art">CABLE</div><h2>STUDIO CABLE</h2><p>무산소 동선 1.5m · ₩39,000</p></article></div></section></main>}
function Support(){return <main><SubHero index="CARE / SUPPORT" title="HOW CAN WE HELP?" copy="제품 설정부터 수리, 배송까지. AURALAB 팀이 빠르게 도와드리겠습니다."/><section className="support-body"><div className="max support-grid"><div className="support-links"><a href="/register"><span>제품 등록</span><b>↗</b></a><a href="/shipping"><span>배송 및 반품</span><b>↗</b></a><a href="/warranty"><span>보증 및 수리</span><b>↗</b></a><a href="/technology"><span>제품 사용 가이드</span><b>↗</b></a></div><form className="support-form"><div className="eyebrow lime">SEND A MESSAGE</div><h2>무엇을 도와드릴까요?</h2><div className="field"><label>이름</label><input placeholder="이름을 입력하세요"/></div><div className="field"><label>이메일</label><input type="email" placeholder="you@example.com"/></div><div className="field"><label>문의 내용</label><textarea rows={5} placeholder="문의 내용을 입력하세요"/></div><button className="cta" type="button">SUBMIT REQUEST ↗</button></form></div></section></main>}
function InfoPage({page}:{page:"shipping"|"warranty"|"register"}){const data={shipping:["DELIVERY / RETURNS","FAST. SIMPLE. FAIR.","평일 오후 2시 이전 주문은 당일 출고됩니다. 모든 헤드셋은 무료 배송이며, 수령 후 30일 이내 무료 반품할 수 있습니다."],warranty:["CARE / WARRANTY","BUILT TO LAST.","HALO X1은 구매일로부터 2년 동안 제조상 결함을 보증합니다. 이어쿠션과 헤드밴드는 교체 가능하며, 전문 엔지니어가 제품을 점검합니다."],register:["PRODUCT / REGISTER","STAY IN THE LOOP.","제품을 등록하면 보증 상태와 수리 이력을 한곳에서 관리하고, 최신 펌웨어와 전용 지원을 받을 수 있습니다."]}[page];return <main><SubHero index={data[0]} title={data[1]} copy={data[2]}/><section className="info-body"><div className="max info-card"><div><span className="eyebrow lime">AURALAB CARE</span><h2>{page==="register"?"제품 시리얼 번호를 입력하세요":page==="shipping"?"배송부터 반품까지":"오래 듣기 위한 약속"}</h2><p>{data[2]}</p></div>{page==="register"?<div className="register-form"><input placeholder="예: AX1-KR-2026-0000"/><button className="cta">REGISTER ↗</button></div>:<a className="cta" href="/support">CONTACT SUPPORT ↗</a>}</div></section></main>}

function Cart({items,setItems}:{items:CartItem[];setItems:(v:CartItem[])=>void}){
  const total=useMemo(()=>items.reduce((s,x)=>s+x.price*x.qty,0),[items]);
  const change=(id:string,qty:number)=>setItems(items.map(x=>x.id===id?{...x,qty:Math.max(1,qty)}:x));
  const remove=(id:string)=>setItems(items.filter(x=>x.id!==id));
  return <main><SubHero index="YOUR BAG" title="SHOPPING BAG." copy="선택한 제품을 확인하고 결제를 진행하세요."/><section className="cart-body"><div className="max">{items.length===0?<div className="cart-empty"><div><h2>장바구니가 비어 있습니다.</h2><p>당신의 일상을 바꿀 사운드를 찾아보세요.</p><br/><a className="cta" href="/products">EXPLORE PRODUCTS ↗</a></div></div>:<div className="cart-layout"><div className="cart-list">{items.map(item=><article className="cart-item" key={item.id}><img src={item.image} alt={`${item.name} ${item.colorKo}`}/><div><small>{item.colorKo}</small><h2>{item.name}</h2><p>{won(item.price)}</p><div className="qty"><button onClick={()=>change(item.id,item.qty-1)}>−</button><span>{item.qty}</span><button onClick={()=>change(item.id,item.qty+1)}>+</button></div></div><button className="remove" onClick={()=>remove(item.id)}>REMOVE</button></article>)}</div><aside className="summary"><span>ORDER SUMMARY</span><div><span>상품 금액</span><b>{won(total)}</b></div><div><span>배송</span><b>FREE</b></div><div className="summary-total"><span>TOTAL</span><b>{won(total)}</b></div><button className="cta">CHECKOUT ↗</button><small>안전한 결제 · 30일 무료 반품</small></aside></div>}</div></section></main>}

export function Storefront({page}:{page:Page}){
  const root=useRef<HTMLDivElement>(null); const [cart,setCartState]=useState<CartItem[]>([]); const [ready,setReady]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem("auralab-cart");if(saved)setCartState(JSON.parse(saved))}finally{setReady(true)}},[]);
  const setCart=(items:CartItem[])=>{setCartState(items);localStorage.setItem("auralab-cart",JSON.stringify(items))};
  const add=(p:Product)=>{const found=cart.find(x=>x.id===p.id);setCart(found?cart.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...cart,{...p,qty:1}])};
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.from(".hero-copy > *",{y:50,opacity:0,duration:1.1,stagger:.12,ease:"power3.out"});gsap.from(".hero-product",{scale:.82,rotate:8,opacity:0,duration:1.35,ease:"power3.out"});if(document.querySelector(".sound-pin")){ScrollTrigger.create({trigger:".sound-lab",start:"top top",end:"bottom bottom",pin:".sound-pin"});gsap.to(".sound-product-frame",{rotate:-8,scale:1.1,scrollTrigger:{trigger:".sound-lab",start:"top top",end:"bottom bottom",scrub:1}});gsap.from(".stat",{y:30,opacity:0,stagger:.15,scrollTrigger:{trigger:".sound-lab",start:"top 20%"}})}gsap.utils.toArray<HTMLElement>(".section-head,.immersive h2,.story-lead,.value,.tech-stack article").forEach(el=>gsap.from(el,{y:60,opacity:0,duration:.9,scrollTrigger:{trigger:el,start:"top 85%"}}))},root);return()=>ctx.revert()},[page]);
  const content=page==="home"?<Home/>:page==="products"?<Products/>:page==="detail"?<Detail add={add}/>:page==="accessories"?<Accessories/>:page==="technology"?<Technology/>:page==="story"?<Story/>:page==="journal"?<Journal/>:page==="support"?<Support/>:page==="shipping"?<InfoPage page="shipping"/>:page==="warranty"?<InfoPage page="warranty"/>:page==="register"?<InfoPage page="register"/>:<Cart items={cart} setItems={setCart}/>;
  return <div ref={root}><Header count={ready?cart.reduce((s,x)=>s+x.qty,0):0}/>{content}<Footer/></div>;
}
